/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 11 17:34:44 GMT 2026
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AdvancedCalculator_ESTest extends AdvancedCalculator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AdvancedCalculator advancedCalculator0 = new AdvancedCalculator();
      boolean boolean0 = advancedCalculator0.isEven(2);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AdvancedCalculator advancedCalculator0 = new AdvancedCalculator();
      boolean boolean0 = advancedCalculator0.isEven(3061);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      AdvancedCalculator advancedCalculator0 = new AdvancedCalculator();
      // Undeclared exception!
      try { 
        advancedCalculator0.divide(306, 0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Division by zero
         //
         verifyException("AdvancedCalculator", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      AdvancedCalculator advancedCalculator0 = new AdvancedCalculator();
      int int0 = advancedCalculator0.divide((-1), (-1304));
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      AdvancedCalculator advancedCalculator0 = new AdvancedCalculator();
      int int0 = advancedCalculator0.add(0, 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      AdvancedCalculator advancedCalculator0 = new AdvancedCalculator();
      int int0 = advancedCalculator0.multiply(347, 306);
      assertEquals(106182, int0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      AdvancedCalculator advancedCalculator0 = new AdvancedCalculator();
      int int0 = advancedCalculator0.subtract(0, 384);
      assertEquals((-384), int0);
  }
}
